version: "2"

services:

  # pulseaudio:
  #   image: jess/pulseaudio
  #   devices:
  #     - /dev/snd
  #   volumes:
  #     - /etc/localtime:/etc/localtime
  #   ports:
  #     - "4713:4713"

#  cups:
#    build: ./cups
#    env_file: .env
#    volumes:
#      - /var/run/dbus:/var/run/dbus
#      - /dev/bus/usb:/dev/bus/usb
#    devices:
#      - /dev/usb
#    command: bash start-cups.sh
#    ports:
#      - "630:631"
#    restart: "always"

  mpd:
    image: tobi312/rpi-mpd:alpine
    ports:
      - "6600:6600"
      - "8000:8000"
    volumes:
      - ./data/folders/Music:/mpd/music:ro
      - ./data/mpd/playlists:/mpd/playlists
      - ./data/mpd/conf:/mpd/conf
      - ./data/mpd/data:/mpd/data
    devices:
      - /dev/snd
    restart: "always"

  ympd:
    build: ./ympd
    ports:
      - "8080:8080"
    links:
      - "mpd:mpdhost"
    depends_on:
      - mpd  
    restart: "always"

  nginx:
    build: ./nginx
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      # - cups
      - sync
      - ympd
    env_file: .env
    restart: always

  sync:
    image: yangxuan8282/rpi-resilio-sync
    ports:
      - "8888:8888"
      - "55554:55555"
    volumes:
      - ./data:/mnt/sync
    env_file: .env
    restart: "always"

  deluge:
    image: jordancrawford/rpi-deluge
    ports:
      - "8112:8112"
      - "58846:58846"
    volumes:
      - ./data:/data
      - ./deluge:/config
    env_file: .env
    restart: "always"