# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storage.models.attachment
import storage.models.record


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Update')),
                ('file', models.FileField(upload_to=storage.models.attachment.content_file_name)),
                ('extension', models.CharField(default='blob', max_length=20, null=True, verbose_name='File extension')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Update')),
                ('uuid', models.TextField(default=storage.models.record.generate_uuid, verbose_name='UUID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Update')),
                ('record_type', models.CharField(choices=[('blob', 'BLOB'), ('music', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('picture', 'Picture')], default='blob', max_length=20, verbose_name='Record type')),
                ('name', models.TextField(verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Record Type',
                'verbose_name_plural': 'Record Types',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='storage.Type'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='storage.Record'),
        ),
        migrations.CreateModel(
            name='RecordProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'proxy': True,
                'indexes': [],
            },
            bases=('storage.record',),
        ),
    ]
